# Site settings 配置站点
title: 'ZEZEST'
description: 'ZEZEST BLOG!'
keyword: 'javascript, nodejs, react, go'
email: zeze.lsh@gmail.com
# if you don't need baseurl, you should leave this value blank.
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'
  goLang: '/goLang.html'

# Footer
footer:
  since: 2018

# Author
author: 'LeeSanghoon'
nickname: 'ZEZE'
bio: 'FRONT-END 개발자'
avatar: '/assets/img/profile.jpg'

# Search
search: true

# Night mode
nightMode: true

# Comments 코멘트 기능
#   default_hidden： 기본적으로 주석을 숨길 지 여부입니다. 그렇다면 버튼을 클릭하여 표시해야합니다. (무슨뜻??..)
comments:
  default_hidden: false
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'

  livere: false
  livere_uid: MTAyMC8yODEwMC80Njcz

# 스크롤 맨위로 올리기 활성 상태
b2t: true

# MathJax 수학기호 사용 활성 상태
mathjax: true

# Share
social-share: false
social-share-items: ['facebook', 'twitter']

# theme color
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: '//github.com/zezest'
  instagram: '//www.instagram.com/isanghoon92'
  email: 'mailto:zeze.lsh@gmail.com'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins_dir: [jekyll-paginate]

gems: [jekyll-paginate]
